package GetSymbolData;


import java.io.*;

public class SymbolPlusList {
	
	String firstTwo = "http://finance.yahoo.com/d/quotes.csv?s=AAMC+ AAU+ ACU+ ADGE+ ADK+ AE+ AIRI+ AKG+ ALN+ AMCO+ AMPE+ AMS+ ANO+ ANV+ ANX+ API+ APP+ APT+ AQQ+ ASM+ ATL+ AUMN+ AVL+ AWX+ AXN+ AXU+ AXX+ AZC+ BAA+ BCV+ BDL+ BFY+ BHB+ BHV+ BKJ+ BKR+ BLE+ BLJ+ BONE+ BPS+ BQI-RWI+ BQY+ BRD+ BTI+ BTN+ BTX+ BVX+ BXE+ BZC+ CAK+ CCA+ CDY+ CEF+ CEP+ CEV+ CFD+ CFP+ CH+ CHGS+ CIK+ CLM+ CMFO+ CMT+ CNAM+ CNR+ COVR+ CPHI+ CQP+ CRF+ CRV+ CRVP+ CTF+ CTO+ CTP+ CUO+ CUR+ CVM+ CVR+ CVU+ CXM+ DEJ+ DGSE+ DHY+ DIT+ DLA+ DMC+ DMF+ DNN+ DPW+ DSS+ DXR+ EAD+ ECBE+ ECF+ EGAS+ EIA+ EIM+ EIO+ EIP+ EIV+ ELLO+ ELMD+ EMAN+ EMI+ EMJ+ EMXX+ ENX+ EOX+ EPM+ ERB+ ERC+ ERH+ ESA+ ESP+ ETAK+ ETF+ ETUA+ ETUB+ EVBN+ EVI+ EVJ+ EVK+ EVM+ EVO+ EVP+ EVV+ EVY+ EXE+ FAX+ FCO+ FCSC+ FEN+ FFI+ FPP+ FRD+ FRS+ FSI+ FSP+ FTF+ FU+ FWV+ GBR+ GGN+ GHM+ GIG+ GIW+ GLO+ GLQ+ GLU+ GLU-PA+ GMO+ GORO+ GPL+ GRC+ GRF+ GRH+ GSB+ GSS+ GST+ GSV+ GTE+ GTT+ GTU+ GV+ GVP+ HEB+ HH+ HMG+ HNW+ HRT+ HTM+ HUSA+ HWG+ IAF+ ICH+ IDI+ IDN+ IEC+ IFMI+ IG+ IGC+ IGC-WT+ IHT+ IMH+ IMO+ IMUC+ INFU+ INO+ IOT+ IPB+ IRT+ ISL+ IVD+ JOB+ JRS+ KBX+ KGN+ LAQ+ LBY+ LCI&f=sn";

}
